export const GAMA_COLORES = {
    rojo: 'red',
    blanco: 'white',
    negro: 'black',
    verde: 'green',
    azul: 'blue',
    amarillo: 'yellow',
    naranja: 'orange',
    morado: 'purple',
    rosa: 'pink',
    gris: 'gray',
    cafe: 'brown',
    turquesa: 'turquoise',
    vinotinto: 'wine',
    plateado: 'silver',
    oro: 'gold',
    verdeagua: 'sea',
    paloRosa: 'rosewood',
    celeste: 'cyan',
    lila: 'lilac',
}